{% set name = "opentelemetry-sdk-extension-aws" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-sdk-extension-aws-{{ version }}.tar.gz
  sha256: c46431857b0b785d9be33c39f43d4cdb93407d17cbaa367320441229e0310a91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - opentelemetry-sdk >=1.3,<2.dev0

test:
  imports:
    - opentelemetry.sdk.extension.aws.trace
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/sdk-extension/opentelemetry-sdk-extension-aws
  summary: AWS SDK extension for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
